# Generated by Django 3.0.5 on 2020-05-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='friend',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
